FROM node:22-alpine
WORKDIR /feedstand

ARG VERSION_TAG
ENV VERSION_TAG=${VERSION_TAG}

COPY package*.json .
COPY tsconfig.json .
COPY apps/backend/package.json apps/backend/
RUN npm ci -w apps/backend --ignore-scripts

COPY apps/backend apps/backend/
EXPOSE 4001
CMD ["npm", "run", "start", "-w", "apps/backend"]
