FROM node:24-alpine
WORKDIR /home/node

ENV VERSION_TAG=dev

COPY package*.json .
COPY tsconfig.json .
COPY apps/backend/package.json apps/backend/
RUN npm ci --ignore-scripts -w apps/backend

COPY . .
EXPOSE 4001
CMD ["npm", "run", "dev", "-w", "apps/backend"]
