FROM node:24-alpine
WORKDIR /home/node

ENV VERSION_TAG=test

COPY package*.json .
COPY tsconfig.json .
COPY apps/backend/package.json apps/backend/
RUN npm ci --ignore-scripts -w apps/backend

COPY . .
CMD ["npm", "run", "test", "-w", "apps/backend"]
