FROM oven/bun:alpine
RUN apk add --no-cache git
WORKDIR /home/bun

ENV VERSION_TAG=dev

COPY package.json bun.lock ./
COPY tsconfig.json ./
COPY apps/backend/package.json apps/backend/
COPY apps/frontend/package.json apps/frontend/
RUN bun install --frozen-lockfile --backend=copyfile --linker=hoisted

COPY . .
EXPOSE 4001
CMD ["bun", "run", "--cwd", "apps/backend", "dev"]
