FROM node:22-alpine
WORKDIR /home/node

ENV VITE_VERSION_TAG=test

COPY package*.json .
COPY tsconfig.json .
COPY apps/frontend/package.json apps/frontend/
RUN bun install --frozen-lockfile --backend=copyfile --linker=hoisted

COPY . .
CMD ["npm", "run", "test", "-w", "apps/frontend"]
