FROM node:22-alpine
WORKDIR /home/node

ENV VITE_VERSION_TAG=test

COPY package*.json .
COPY tsconfig.json .
COPY apps/frontend/package.json apps/frontend/
RUN npm ci -w apps/frontend --ignore-scripts

COPY apps/frontend apps/frontend/
CMD ["npm", "run", "test", "-w", "apps/frontend"]
