FROM node:22-alpine
WORKDIR /home/node

ENV VITE_VERSION_TAG=dev

COPY package*.json .
COPY tsconfig.json .
COPY apps/frontend/package.json apps/frontend/
RUN bun install --frozen-lockfile --backend=copyfile --linker=hoisted

COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev", "-w", "apps/frontend"]
