x-common-deploy: &common-deploy
  replicas: 1
  update_config:
    parallelism: 1
    order: start-first
    failure_action: rollback
  restart_policy:
    condition: any

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  frontend:
    image: feedstand/frontend:${VERSION_TAG}
    environment:
      BACKEND_URL: ${FRONTEND_BACKEND_URL}
      SENTRY_DSN: ${FRONTEND_SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${FRONTEND_SENTRY_ENVIRONMENT}
    ports:
      - 4000:4000
    deploy:
      <<: *common-deploy
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:4000"]

  backend:
    image: feedstand/backend:${VERSION_TAG}
    environment:
      SERVER_HOST: ${BACKEND_SERVER_HOST}
      SERVER_PORT: ${BACKEND_SERVER_PORT}
      DATABASE_HOST: ${BACKEND_DATABASE_HOST}
      DATABASE_PORT: ${BACKEND_DATABASE_PORT}
      DATABASE_NAME: ${BACKEND_DATABASE_NAME}
      DATABASE_USER: ${BACKEND_DATABASE_USER}
      DATABASE_PASS: ${BACKEND_DATABASE_PASS}
      QUEUE_HOST: ${BACKEND_QUEUE_HOST}
      QUEUE_PORT: ${BACKEND_QUEUE_PORT}
      SENTRY_DSN: ${BACKEND_SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${BACKEND_SENTRY_ENVIRONMENT}
    ports:
      - 4001:4001
    deploy:
      <<: *common-deploy
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:4001"]

  database:
    image: postgres:17-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASS}
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "pg_isready -U ${BACKEND_DATABASE_USER}"]

  queue:
    image: redis:7-alpine
    deploy:
      <<: *common-deploy
    ports:
      - 6379:6379
    volumes:
      - ./data/queue:/data
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "redis-cli", "ping"]
