x-common-deploy: &common-deploy
  update_config:
    order: start-first
    failure_action: rollback
  restart_policy:
    condition: on-failure

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 30s

x-common-logging: &common-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-backend-config: &backend-config
  image: ghcr.io/feedstand/backend:${VERSION_TAG:-latest}
  depends_on:
    - pgbouncer
    - database

x-backend-environment: &backend-environment
  SERVER_HOST: 0.0.0.0
  SERVER_PORT: 4001
  DATABASE_HOST: pgbouncer
  DATABASE_NAME: ${BACKEND_DATABASE_NAME}
  DATABASE_USER: ${BACKEND_DATABASE_USER}
  DATABASE_PASS: ${BACKEND_DATABASE_PASS}
  QUEUE_HOST: queue
  SENTRY_DSN: ${BACKEND_SENTRY_DSN}
  SENTRY_ENVIRONMENT: ${BACKEND_SENTRY_ENVIRONMENT}

services:
  traefik:
    image: traefik:3
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    command:
      # Swarm Provider
      - --providers.docker=false
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Global HTTP → HTTPS Redirect
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      # Let's Encrypt with DNS Challenge (Cloudflare)
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Logging
      - --log.level=INFO
      - --accesslog.filepath=/logs/access.log
      - --accesslog.bufferingsize=100
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Replaces: Cloudflare HSTS, Automatic HTTPS Rewrites
        - traefik.http.middlewares.shared-security.headers.stsSeconds=31536000
        - traefik.http.middlewares.shared-security.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.shared-security.headers.stsPreload=true
        - traefik.http.middlewares.shared-security.headers.forceSTSHeader=true
        - traefik.http.middlewares.shared-security.headers.contentSecurityPolicy=upgrade-insecure-requests
        - traefik.http.middlewares.shared-security.headers.frameDeny=true
        - traefik.http.middlewares.shared-security.headers.contentTypeNosniff=true
        - traefik.http.middlewares.shared-security.headers.referrerPolicy=strict-origin-when-cross-origin
        - traefik.http.middlewares.shared-security.headers.customResponseHeaders.server=
        # Enable GZIP Compression
        - traefik.http.middlewares.compression.compress=true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
    networks:
      - public
    logging:
      <<: *common-logging

  dozzle:
    image: amir20/dozzle:latest
    environment:
      DOZZLE_MODE: swarm
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.http.routers.dozzle.rule=Host(`logs.feedstand.com`)
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls=true
        - traefik.http.routers.dozzle.tls.certresolver=letsencrypt
        - traefik.http.routers.dozzle.middlewares=shared-security@swarm
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
        # ⚠️ Add HTTP Basic Authentication
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
    logging:
      <<: *common-logging

  frontend:
    image: ghcr.io/feedstand/frontend:${VERSION_TAG:-latest}
    environment:
      BACKEND_URL: ${FRONTEND_BACKEND_URL}
      SENTRY_DSN: ${FRONTEND_SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${FRONTEND_SENTRY_ENVIRONMENT}
    deploy:
      <<: *common-deploy
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`app.feedstand.com`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.routers.frontend.tls=true
        - traefik.http.routers.frontend.tls.certresolver=letsencrypt
        - traefik.http.routers.frontend.middlewares=shared-security@swarm
        - traefik.http.services.frontend.loadbalancer.server.port=4000
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "wget", "-q", "--spider", "--method=HEAD", "http://0.0.0.0:4000/health"]
    networks:
      - public
    logging:
      <<: *common-logging

  backend-server:
    <<: *backend-config
    environment:
      <<: *backend-environment
      FEATURE_MIGRATOR: "true"
      FEATURE_SERVER: "true"
    deploy:
      <<: *common-deploy
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.backend.rule=Host(`api.feedstand.com`)
        - traefik.http.routers.backend.entrypoints=websecure
        - traefik.http.routers.backend.tls=true
        - traefik.http.routers.backend.tls.certresolver=letsencrypt
        - traefik.http.routers.backend.middlewares=shared-security@swarm
        - traefik.http.services.backend.loadbalancer.server.port=4001
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:4001"]
    networks:
      - public
      - internal
    logging:
      <<: *common-logging

  backend-worker:
    <<: *backend-config
    environment:
      <<: *backend-environment
      FEATURE_WORKER: "true"
    deploy:
      <<: *common-deploy
      replicas: 30
      update_config:
        parallelism: 4
        delay: 30s
        order: start-first
      placement:
        max_replicas_per_node: 10
        constraints:
          - node.role != manager
          - node.labels.worker == true
        preferences:
          - spread: node.id
    networks:
      - internal
    logging:
      <<: *common-logging

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      DB_HOST: database
      DB_NAME: ${BACKEND_DATABASE_NAME}
      DB_USER: ${BACKEND_DATABASE_USER}
      DB_PASSWORD: ${BACKEND_DATABASE_PASS}
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 500
      DEFAULT_POOL_SIZE: 50
      MAX_DB_CONNECTIONS: 100
      RESERVE_POOL_SIZE: 25
      RESERVE_POOL_TIMEOUT: 5
      ADMIN_USERS: ${BACKEND_DATABASE_USER}
      AUTH_TYPE: scram-sha-256
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      <<: *common-deploy
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "${BACKEND_DATABASE_USER}"]
    depends_on:
      - database
    networks:
      - internal
    logging:
      <<: *common-logging

  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASS}
    deploy:
      <<: *common-deploy
      placement:
        constraints:
          - node.role == manager
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "${BACKEND_DATABASE_USER}"]
    logging:
      <<: *common-logging

  queue:
    image: redis:7-alpine
    command:
      - "redis-server"
      - "--save ''"
      - "--appendonly yes"
      - "--appendfsync everysec"
      - "--no-appendfsync-on-rewrite yes"
      - "--auto-aof-rewrite-percentage 100"
      - "--auto-aof-rewrite-min-size 256mb"
      - "--aof-rewrite-incremental-fsync yes"
      - "--maxmemory-policy noeviction"
      - "--aof-use-rdb-preamble yes"
    deploy:
      <<: *common-deploy
      placement:
        constraints:
          - node.role == manager
    volumes:
      - queue_data:/data
    networks:
      - internal
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD", "redis-cli", "ping"]
    logging:
      <<: *common-logging

volumes:
  letsencrypt_data:
    driver: local
  database_data:
    driver: local
  queue_data:
    driver: local

networks:
  public:
    driver: overlay
    attachable: true
  internal:
    driver: overlay
    internal: true
